name: 'EdTech Pipeline - Security Scan'
description: 'Security scanning with bandit for EdTech Student Success Pipeline'

runs:
  using: composite
  steps:
    - name: Run bandit security scan
      run: uv run bandit -r src/ apps/ -ll -f json -o bandit-report.json || true
      shell: bash
      continue-on-error: true
    
    - name: Display bandit results
      run: uv run bandit -r src/ apps/ -ll
      shell: bash
      continue-on-error: true
