name: 'EdTech Pipeline - Linting'
description: 'Quality checks with ruff for EdTech Student Success Pipeline'

runs:
  using: composite
  steps:
    - name: Run ruff linting
      run: uv run ruff check src/ apps/ tests/
      shell: bash
      continue-on-error: true
    
    - name: Run mypy type checking
      run: uv run mypy src/ apps/
      shell: bash
      continue-on-error: true
