name: 'EdTech Pipeline - Run Tests'
description: 'Run pytest suite for EdTech Student Success Pipeline'

inputs:
  python-version:
    required: false
    default: '3.11'
    description: 'Python version'
  
  coverage-threshold:
    required: false
    default: '70'
    description: 'Minimum coverage % required'

runs:
  using: composite
  steps:
    - name: Run tests with coverage
      run: |
        uv run pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=html \
          --cov-report=term-missing \
          -v
      shell: bash
      continue-on-error: false
    
    - name: Upload coverage artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-py${{ inputs.python-version }}
        path: |
          coverage.xml
          htmlcov/
